//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
//±±±±±±±
//±±±±±±± SystemR Version 3.0   By Hlod-Wig of Anaconda Software
//±±±±±±±
//±±±±±±±
//±±±±±±±
//±±±±±±±
//±±±±±±±
//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#ifndef SystemR_V30_Textures
#define SystemR_V30_Textures
//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
#include "..\RDEFINES\RDEFINES.H"
//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±

void GetTextureColor(ProceduralTexture *Texture,TVertex &CH,TReal Scale,TReal InvScale,RealColor &Color);

//±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
extern short   *hashTable;
extern TReal   RTable[267];
extern int Std_rand();
extern void Std_srand(int seed);
extern void CloseTextureTable();
extern void InitTextureTable();
extern TReal Noise(TVertex EPoint);
extern TReal Turbulence(TVertex EPoint,DefTurb *Turb);
extern void GetTextInfo (ProceduralTexture *TXT0,TReal Scale,TReal InvScale,TVertex &CH,RealColor &Col0);
extern void GetTextureColor(ProceduralTexture *Texture,TVertex &CH,TReal Scale,TReal InvScale,RealColor &Color);
#endif
